title: Festival de Cinema de Diamantina
description: "Em breve informações sobre o IIº Cine Diamante."
baseurl: "" # leave empty unless deployed in a subdirectory
url: "https://cinediamante.com.br" # set your production URL
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Additional Netlify settings (if needed)
markdown: kramdown


image_path: /assets/images
assets_path: /assets
