title: Your Site Title
description: "A brief description of your site."
baseurl: "" # leave empty unless deployed in a subdirectory
url: "https://yourdomain.com" # set your production URL
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Additional Netlify settings (if needed)
markdown: kramdown


image_path: /images
